// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' }
  ],

  // But you can create a sidebar manually
  documentationSidebar: [
    {
      type: 'doc',
      id: 'home',
      label: 'หน้าหลัก'
    },
    {
      type: 'category',
      label: '📍 สถานะ',
      items: [
        {
          type: 'doc',
          id: 'statuses/sales-order',
          label: '📦 สถานะคำสั่งซื้อ'
        },
        {
          type: 'doc',
          id: 'statuses/shipment',
          label: '🚚 สถานะการจัดส่ง'
        },
        {
          type: 'doc',
          id: 'statuses/payment',
          label: '💰 สถานะการชำระเงิน'
        }
      ]
    }
  ]
};

export default sidebars;
